version: "3.9"

services:
  

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
      tags:
      - amandevars/mpssctyping-server:v1
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
